---
title: "Create metanetwork"
output: html_document
date: "2024-02-15"
---

# 0. Load packages and import data

```{r warning=FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(readxl)
library(stringr)
library(taxize)
library(rgbif)
```

```{r message=FALSE, warning=FALSE}
macrofaune_surface_0 <- read_delim("data/1. barber_taxo2023-09-26.csv", show_col_types = FALSE)[,-1]

macrofaune_aerial_0 <- read_csv("data/1. pantrap_taxo2023-09-08.csv", show_col_types = FALSE)[,-1] # read_delim doesn't work for me (anne-so)

macrofaune_foliar_0 <- read_csv("data/clean_data_robinier_2023-09-16.csv", show_col_types =  FALSE)[,-1]

micro_arthropodes_all_0 <- read_excel("data/NH_Tri_mesofaune - INRAE MONTPELLER_AM_MH.xlsx")[,-c(11,12)]
micro_arthropodes_col_0 <- read_excel("data/BDD Collemboles - INRAE MONTPELLIER.xlsx")

nematodes_a_0 <- read_excel("data/Communautés_avril vf.xlsx", sheet = "Feuil1")
nematodes_m_0 <- read.table("data/ifossa.mars.txt", header= TRUE )

bacteria_0 <- read_delim("data/OTU_Table_Bacterie.tsv")[,c(0:72)]

fungi_0 <- read_delim("data/OTU_Table_Champignon.tsv")[,c(0:72)]

cercozoa_0 <- read_delim("data/OTU_Table_Cercozoa.tsv")[,c(0:72)]

metadata_mo_0 <- read_delim("data/mapping_brut.csv")
```

# 1. Tidy data

## macrofaune_surface

```{r}
macrofaune_surface_1 <- macrofaune_surface_0

# rename columns
macrofaune_surface_1 <- macrofaune_surface_1 %>%  rename(block = bloc, replicate = rep)

# add column method and date
macrofaune_surface_1 <- macrofaune_surface_1 %>% mutate(method = "barber_trap")
macrofaune_surface_1 <- macrofaune_surface_1 %>% mutate(date = "XX/2023")

# homogeneise code
macrofaune_surface_1$usage[macrofaune_surface_1$usage == 'C'] <- 'MC'
macrofaune_surface_1$usage[macrofaune_surface_1$usage == 'F'] <- 'TP'

macrofaune_surface_1$block[macrofaune_surface_1$block == '1'] <- 'B1'
macrofaune_surface_1$block[macrofaune_surface_1$block == '2'] <- 'B2'
macrofaune_surface_1$block[macrofaune_surface_1$block == '3'] <- 'B3'

macrofaune_surface_1$habitat[macrofaune_surface_1$habitat == 'Cult' | macrofaune_surface_1$habitat == 'cult' ] <- 'C'
macrofaune_surface_1$habitat[macrofaune_surface_1$habitat == 'Forest' | macrofaune_surface_1$habitat == 'LSA' ] <- 'T'

macrofaune_surface_1$replicate[macrofaune_surface_1$replicate == '1'] <- 'R1'
macrofaune_surface_1$replicate[macrofaune_surface_1$replicate == '2'] <- 'R2'
macrofaune_surface_1$replicate[macrofaune_surface_1$replicate == '3'] <- 'R3'
macrofaune_surface_1$replicate[macrofaune_surface_1$replicate == '4'] <- 'R4'
macrofaune_surface_1$replicate[macrofaune_surface_1$replicate == '5'] <- 'R5'

# create column full_uhbr
macrofaune_surface_1$full_uhbr <- paste(macrofaune_surface_1$usage, macrofaune_surface_1$habitat, macrofaune_surface_1$block, macrofaune_surface_1$replicate, sep = "_")
```

## macrofaune_aerial

```{r }
macrofaune_aerial_1 <- macrofaune_aerial_0

# rename columns
macrofaune_aerial_1 <- macrofaune_aerial_1 %>%  rename(block = bloc, replicate = rep)

# add column method and date
macrofaune_aerial_1 <- macrofaune_aerial_1 %>% mutate(method = "pan_trap")
macrofaune_aerial_1 <- macrofaune_aerial_1 %>%
  mutate(date = case_when(
    grepl('03/23', month) ~ "03/2023",
    grepl('04/23', month) ~ "04/2023"))

# homogeneise code
macrofaune_aerial_1$usage[macrofaune_aerial_1$usage == 'C'] <- 'MC'
macrofaune_aerial_1$usage[macrofaune_aerial_1$usage == 'F'] <- 'TP'

macrofaune_aerial_1$block[macrofaune_aerial_1$block == '1'] <- 'B1'
macrofaune_aerial_1$block[macrofaune_aerial_1$block == '2'] <- 'B2'
macrofaune_aerial_1$block[macrofaune_aerial_1$block == '3'] <- 'B3'

macrofaune_aerial_1$habitat[macrofaune_aerial_1$habitat == 'Cult' | macrofaune_aerial_1$habitat == 'cult' ] <- 'C'
macrofaune_aerial_1$habitat[macrofaune_aerial_1$habitat == 'Forest' | macrofaune_aerial_1$habitat == 'LSA' ] <- 'T'

macrofaune_aerial_1$replicate[macrofaune_aerial_1$replicate == '1'] <- 'R1'
macrofaune_aerial_1$replicate[macrofaune_aerial_1$replicate == '2'] <- 'R2'
macrofaune_aerial_1$replicate[macrofaune_aerial_1$replicate == '3'] <- 'R3'
macrofaune_aerial_1$replicate[macrofaune_aerial_1$replicate == '4'] <- 'R4'
macrofaune_aerial_1$replicate[macrofaune_aerial_1$replicate == '5'] <- 'R5'

# create column full_uhbr
macrofaune_aerial_1$full_uhbr <- paste (macrofaune_aerial_1$usage, macrofaune_aerial_1$habitat, macrofaune_aerial_1$block, macrofaune_aerial_1$replicate, sep = "_")
```

## macrofaune_foliar

```{r}
macrofaune_foliar_1 <- macrofaune_foliar_0

# modify column method
macrofaune_foliar_1$method[macrofaune_foliar_0$method == 'rameau'] <- 'twig'
macrofaune_foliar_1$method[macrofaune_foliar_1$method == 'dissection inflo'] <- 'inflorescence'

# add column date and habitat
macrofaune_foliar_1 <- macrofaune_foliar_1 %>% mutate(date = "XX/2023")
macrofaune_foliar_1 <- macrofaune_foliar_1 %>% mutate(habitat = "T")

# homogeneise code
macrofaune_foliar_1 <- macrofaune_foliar_1 %>% 
   separate(col = usage_bloc , into = c("usage","block","rang","arbre"), sep = "_")

macrofaune_foliar_1 <- macrofaune_foliar_1 %>% mutate(across('rang', str_replace, 'arbre', ''))
  
macrofaune_foliar_1 <- macrofaune_foliar_1 %>% 
   mutate(rang = gsub("rang", "R", rang)) 

macrofaune_foliar_1 <- macrofaune_foliar_1 %>% 
  mutate(arbre = gsub("arbre", "", arbre))

macrofaune_foliar_1 <- macrofaune_foliar_1 %>% 
  mutate(replicate = paste(rang, arbre ,sep="."))

macrofaune_foliar_1$block[macrofaune_foliar_1$block == '1'] <- 'B1'
macrofaune_foliar_1$block[macrofaune_foliar_1$block == '2'] <- 'B2'
macrofaune_foliar_1$block[macrofaune_foliar_1$block == '3'] <- 'B3'

# create column full_uhbr
macrofaune_foliar_1$full_uhbr <- paste (macrofaune_foliar_1$usage, macrofaune_foliar_1$habitat, macrofaune_foliar_1$block, macrofaune_foliar_1$replicate, sep = "_")
```

## nematodes

### march

```{r}
nematodes_m_1 <- nematodes_m_0

# add columns date, method and replicate
nematodes_m_1 <- nematodes_m_1 %>% mutate(date = "03/2023")
nematodes_m_1 <- nematodes_m_1 %>% mutate(method = "baermann")
nematodes_m_1 <- nematodes_m_1 %>% mutate(replicate = "R1")

# homogeneise code
nematodes_m_1 <- nematodes_m_1 %>%
  mutate(usage = case_when(
    startsWith(Taxa, "C") ~ "MC",
    startsWith(Taxa, "AF") ~ "AF",
    startsWith(Taxa, "F") ~ "TP"),
        habitat = case_when(
    grepl('^C|^AF_C', Taxa) ~ "C",
    grepl('^F|^AF_A', Taxa) ~ "T"),
        block = paste0("B", parse_number(Taxa)))

# create column full_uhbr
nematodes_m_1$full_uhbr <- paste(nematodes_m_1$usage, nematodes_m_1$habitat, nematodes_m_1$block, nematodes_m_1$replicate, sep="_")
```

### april

```{r}
nematodes_a_1 <- nematodes_a_0

# add columns date, method and replicate
nematodes_a_1 <- nematodes_a_1 %>% mutate(date = "04/2023")
nematodes_a_1 <- nematodes_a_1 %>% mutate(method = "baermann")
nematodes_a_1 <- nematodes_a_1 %>% mutate(replicate = "R1")

# homogeneise code
nematodes_a_1 <- nematodes_a_1 %>%
 mutate(usage = case_when(
    grepl('[[:digit:]]C', Taxa) ~ "MC",
    grepl('[[:digit:]]AF', Taxa) ~ "AF",
    grepl('[[:digit:]]F', Taxa) ~ "TP"),
        habitat = case_when(
    grepl('C$', Taxa) ~ "C",
    grepl('F$|A$', Taxa) ~ "T"),
        block = paste0("B", parse_number(Taxa)))

# create column full_uhbr
nematodes_a_1$full_uhbr <- paste(nematodes_a_1$usage, nematodes_a_1$habitat, nematodes_a_1$block, nematodes_a_1$replicate, sep="_")
```

### all

```{r}
# bind and pivot data
nematodes_1 <- bind_rows(nematodes_a_1, nematodes_m_1)
nematodes_1 <- nematodes_1 %>% replace(is.na(.), 0)
nematodes_1 <- nematodes_1 %>% select(Taxa, full_uhbr, usage, habitat, block, replicate, date, method, everything())
nematodes_1 <- pivot_longer(nematodes_1, cols = c(9:38), names_to =  "taxa", values_to = "abundance")

nematodes_1 <- nematodes_1 %>% rename(name=taxa)
nematodes_1$abundance <- lapply(nematodes_1$abundance, round)
```

## micro-arthropodes

```{r}
micro_arthropodes_all_1 <- micro_arthropodes_all_0

# delete 3 last rows (they are not samples)
micro_arthropodes_all_1 <- micro_arthropodes_all_1 %>% slice(-c(346:348))

# remplace NA by 0 for abundance
micro_arthropodes_all_1 <- micro_arthropodes_all_1 %>%
  mutate(Nbr_identifiés = ifelse(is.na(Nbr_identifiés), 0, Nbr_identifiés),
         Nbr_ind_tri = ifelse(is.na(Nbr_ind_tri), 0, Nbr_ind_tri))

# add column Nbr_individus_final = Nbr_ind_tri - Nbr_identifiés
## Nbr_ind_tri is the total number of individuals
## Nbr_identifiés is the number of collembola more precisely identified
## Nbr_individus_final is needed because not all collembola have been identified
micro_arthropodes_all_1$Nbr_ind_tri <- as.numeric(micro_arthropodes_all_1$Nbr_ind_tri)
micro_arthropodes_all_1$Nbr_identifiés <- as.numeric(micro_arthropodes_all_1$Nbr_identifiés) 

micro_arthropodes_all_1 <- transform(micro_arthropodes_all_1, Nbr_individus_final = Nbr_ind_tri - Nbr_identifiés)

# add collembola identified
micro_arthropodes_all_1 <- micro_arthropodes_all_1 %>% 
  rename(Sites=Num_prélevement)

micro_arthropodes_1 <- bind_rows(micro_arthropodes_all_1, micro_arthropodes_col_0)

# add a unique column abundance
micro_arthropodes_1 <- micro_arthropodes_1 %>% mutate(abundance = coalesce(Nbr_individus_final, Nbr_individus))
micro_arthropodes_1 <- micro_arthropodes_1 %>% mutate(name = coalesce(Noms_espèces, best_ID))
```

```{r}
micro_arthropodes_2 <- micro_arthropodes_1

# add columns date and method
micro_arthropodes_2 <- micro_arthropodes_2 %>% mutate(date = "XX/2023")
micro_arthropodes_2 <- micro_arthropodes_2 %>% mutate(method = "macfayden")

# homogeneise code
micro_arthropodes_2 <- micro_arthropodes_2 %>%
 mutate(usage = case_when(
    grepl('C[[:digit:]]_', Sites) ~ "MC",
    grepl('AF[[:digit:]]_', Sites) ~ "AF",
    grepl('F[[:digit:]]_', Sites) ~ "TP"),
        habitat = case_when(
    grepl('C[[:digit:]]_|AF[[:digit:]]_C', Sites) ~ "C",
    grepl('F[[:digit:]]_|AF[[:digit:]]_LSA', Sites) ~ "T"),
        block = case_when(
    grepl('1_', Sites) ~ "B1",
    grepl('2_', Sites) ~ "B2",
    grepl('3_', Sites) ~ "B3"),
        replicate = case_when(
    grepl('_C1|_LSA1', Sites) ~ "R1",
    grepl('_C2|_LSA2', Sites) ~ "R2",
    grepl('_C3|_LSA3', Sites) ~ "R3",
    grepl('_C4|_LSA4', Sites) ~ "R4",
    grepl('_C5|_LSA5', Sites) ~ "R5"))

# create column full_uhbr
micro_arthropodes_2$full_uhbr <- paste(micro_arthropodes_2$usage, micro_arthropodes_2$habitat, micro_arthropodes_2$block, micro_arthropodes_2$replicate, sep="_")
```

## micro-organisms

```{r}
metadata_mo_1 <- metadata_mo_0

# rename columns
metadata_mo_1 <- metadata_mo_1[c(1:60),] %>%  rename(block = Bloc, replicate = REP, habitat = HABITAT)

# add column method and date
metadata_mo_1 <- metadata_mo_1 %>% mutate(method = "metabarcoding")
metadata_mo_1 <- metadata_mo_1 %>% mutate(date = "XX/2023")

# homogeneise code
metadata_mo_1$usage[metadata_mo_1$usage == 'C'] <- 'MC'
metadata_mo_1$usage[metadata_mo_1$usage == 'F'] <- 'TP'

metadata_mo_1$block <- paste0("B", parse_number(metadata_mo_1$block))

metadata_mo_1$habitat[metadata_mo_1$habitat == 'Tree_line' | metadata_mo_1$habitat == 'Tree_plantation' ] <- 'T'
metadata_mo_1$habitat[metadata_mo_1$habitat == 'Crop' ] <- 'C'

metadata_mo_1$replicate <- paste0("R", parse_number(metadata_mo_1$replicate))

# create column full_uhbr
metadata_mo_1$full_uhbr <- paste (metadata_mo_1$usage, metadata_mo_1$habitat, metadata_mo_1$block, metadata_mo_1$replicate, sep = "_")
```

### bacteria

```{r}
bacteria_1 <- bacteria_0

bacteria_1 <- pivot_longer(bacteria_1, cols = c(13:72), names_to =  "Reference_ADNid", values_to = "abundance", names_repair = "minimal")

bacteria_1$Reference_ADNid <- str_replace(bacteria_1$Reference_ADNid, '_.+_.+', "")

bacteria_1 <- left_join(bacteria_1, metadata_mo_1, by = "Reference_ADNid")
```

### fungi

```{r}
fungi_1 <- fungi_0

fungi_1 <- pivot_longer(fungi_1, cols = c(13:72), names_to =  "Reference_ADNid", values_to = "abundance", names_repair = "minimal")

fungi_1$Reference_ADNid <- str_replace(fungi_1$Reference_ADNid, '_.+_.+', "")

fungi_1 <- left_join(fungi_1, metadata_mo_1, by = "Reference_ADNid")
```

### protists

```{r}
cercozoa_1 <- cercozoa_0

cercozoa_1 <- pivot_longer(cercozoa_1, cols = c(13:72), names_to =  "Reference_ADNid", values_to = "abundance", names_repair = "minimal")

cercozoa_1$Reference_ADNid <- str_replace(cercozoa_1$Reference_ADNid, '_.+_.+', "")

cercozoa_1 <- left_join(cercozoa_1, metadata_mo_1, by = "Reference_ADNid")
```

# Prepare combined file

```{r}
# Select minimal data

fun_macrofaune_surface_0 <- macrofaune_surface_1 %>% 
  select(full_uhbr, name, fullName, genusName, familyName, orderName, className, phylumName, abundance, method, date) # stade and mass can be used for traits

fun_macrofaune_aerial_0 <- macrofaune_aerial_1 %>% 
  select(full_uhbr, name, fullName, genusName, familyName, orderName, className, phylumName, abundance, method, date) # INat can be used for ID and stade can be used for traits

fun_macrofaune_foliar_0 <- macrofaune_foliar_1 %>% 
  select(full_uhbr, name, fullName, genusName, familyName, orderName, className, phylumName, abundance, method, date) # Valid.Name (what is it?)

fun_nematodes_0 <- nematodes_1 %>% select(full_uhbr, name, abundance, method, date)

fun_micro_arthropodes_0 <- micro_arthropodes_2 %>% select(full_uhbr, name, higher.level, lower.level, abundance, method, date) # stade can be used for traits

fun_bacteria_0 <- bacteria_1 %>% 
  select(full_uhbr, blast_taxonomy, abundance, method, date) # seed.id can be used for ID

fun_fungi_0 <- fungi_1 %>% 
  select(full_uhbr, blast_taxonomy, abundance, method, date) # seed.id can be used for ID

fun_cercozoa_0 <- cercozoa_1 %>% 
  select(full_uhbr, blast_taxonomy, abundance, method, date) # seed.id can be used for ID
```

```{r}
# Homogeneise taxonomy
### fun_micro_arthropodes_0 USE TAXIZE before to have rankName, fullname, genusName, familyName, orderName, className and phylumName instead of name, higher.level and lower.level

library(taxize)
 # Create dataframe to store taxonomic information
 harmo_colnames <- c("name", "rankName", "fullName", 
                     "genusName", "familyName", "orderName", "className", "phylumName")
 taxo_micro_arth <- data.frame(matrix(data = NA, 
                                 nrow = 0,  # Start with 0 rows
                                 ncol = length(harmo_colnames),
                                 dimnames = list(NULL, harmo_colnames)))
 
fun_micro_arthropodes_1 <- fun_micro_arthropodes_0 %>%
  tibble(tax_name(unique (fun_micro_arthropodes_0$name), get = c("kingdom", "phylum", "class", "order", "family", "genus"), db = "ncbi")) %>% 
  unnest(fun_micro_arthropodes_1) %>% 
  filter(rank %in% c("kingdom", "phylum","class","order","family","genus")) %>% 
  select(name = kingdomName, phylumName, className, orderName, familyName, genusName)

  
test <- tbl_df(tax_name("Acaridida", get = c("kingdom", "phylum", "class", "order", "family", "genus"), db = "ncbi"))

### fun_nematodes_0 USE TAXIZE before to have rankName, fullname, genusName, familyName, orderName, className and phylumName instead of name

fun_nematodes_1 <- fun_nematodes_0 %>%
  tibble(tax_name(unique( fun_nematodes_0$name), get = c("kingdom", "phylum", "class", "order", "family", "genus"), db = "ncbi")) %>% 
  unnest() %>% 
  filter(rank %in% c("kingdom", "phylum","class","order","family","genus")) %>% 
  select(-query) %>% 
  spread(rank, name) %>% 
  select(name = kingdomName, phylumName, className, orderName, familyName, genusName)


test_1 <- tbl_df(tax_name(fun_nematodes_0[1:5,]$name, get = c("kingdom", "phylum", "class", "order", "family", "genus"), db = "itis"))

test_2 <- tbl_df(tax_name("Pratylenchus", get = c("kingdom", "phylum", "class", "order", "family", "genus"), db = "itis"))

# already done for micro-organisms
fun_bacteria_1 <- fun_bacteria_0 %>% 
   separate(col = blast_taxonomy , into = c("kingdomName","phylumName","className","orderName", "familyName", "genusName", "speciesName"), sep = ";")

fun_fungi_1 <- fun_fungi_0
fun_fungi_1$blast_taxonomy <- str_replace_all(fun_fungi_1$blast_taxonomy, '.__', "")

fun_fungi_1 <- fun_fungi_1 %>% 
   separate(col = blast_taxonomy , into = c("kingdomName","phylumName","className","orderName", "familyName", "genusName", "speciesName"), sep = ";")

fun_cercozoa_1 <- fun_cercozoa_0 %>% 
   separate(col = blast_taxonomy , into = c("kingdomName","phylumName","className","orderName", "familyName", "genusName", "speciesName"), sep = ";")
```

```{r}
# Combine data
fun_all <- bind_rows(fun_macrofaune_surface_1, fun_macrofaune_aerial_1, fun_macrofaune_foliar_1, fun_nematodes_1, fun_micro_arthropodes_1, fun_bacteria_1, fun_fungi_1, fun_cercozoa_1)
```

# 2. Functionnal assignment

# 3. Redundancy analysis



