---
title: "Lines Anne-So"
output: html_document
date: "2024-02-19"
---

```{r message=FALSE}
library(readr)
library(dplyr)
```


```{r message=FALSE}
# Data from Agnes 23lib26
#bacteries_0 <- read_delim("data/Bacterial_Rarefied_OTU_TABLE_cleanned.csv")[,-c(1:2)]
#champignons_0 <- read_delim("data/Champignon_OTU_table.tsv")[,-1]
#protistes_0 <- read_delim("data/protistes_rarefied_OTU_TABLE.csv")[,-1]

# sample code
# for bacteries_0 and champignons_0
# 23MET01624-10-Purif_S104_L001
# 23MET01625-10-Purif_S105_L001
# 23MET01626-10-Purif_S112_L001
# 23MET01627-10-Purif_S113_L001
# for protistes_0
# 23MET01624-10-Purif.S615F_CerS947R_Cer
# 23MET01625-10-Purif.S615F_CerS947R_Cer
# 23MET01626-10-Purif.S615F_CerS947R_Cer
# 23MET01627-10-Purif.S615F_CerS947R_Cer
# BL-PCR-Robin_S121_L001

# Data from Agnes IFOSSA_Septembre 2023_ARviaDD
# sample code

23MET[1942-2025]_S[1-84]_L001
BL-EXT-[1-3]_S[85-87]_L001
BL-PCR_S88_L001

bacteries_0 <- read_delim("data/OTU_Table_Bacterie.tsv")
champignons_0 <- read_delim("data/OTU_Table_Champignon.tsv")
protistes_0 <- read_delim("data/OTU_Table_Cercozoa.tsv")
```

```{r}



```

