---
title: "NA"
output: html_document
date: "2024-05-29"
---

```{r}
library(GratinNavigatoR)
endpoint_url <- "http://129.88.204.79:7200/repositories/gratin"
```

```{r}
# ancienne taxo
oldtax_table <- read.csv("final_files/tax_table/tax_table_update26-04-24.csv")[,-1]

macrofauna_surface_oldtax <- subset(oldtax_table, community == 'macrofaune_surface')

n_distinct(macrofauna_surface_oldtax$family) # 63

macrofauna_surface_guilds_family_oldtax <- get.guilds(sciName = unique(macrofauna_surface_oldtax$family), endpoint = endpoint_url)

n_distinct(macrofauna_surface_guilds_family_oldtax$queryName) # 57
```

```{r}
# nouvelle taxo
tax_table <- read.csv("final_files/tax_table/tax_table_update21-05-24.csv")[,-1]

macrofauna_surface_tax <- subset(tax_table, community == 'macrofauna_surface')

n_distinct(macrofauna_surface_tax$family) # 63

unique_list <- unique(macrofauna_surface_tax$family)
unique_list <- unique_list[unique_list != "unassigned"]
split_list <- split(unique_list, ceiling(seq_along(unique_list)/9))

## guilds
### all taxa at a time
macrofauna_surface_guilds_family_tax <- get.guilds(sciName = unique_list, endpoint = endpoint_url)

n_distinct(macrofauna_surface_guilds_family_tax$queryName) # 57 ou 2 pour 2 runs à quelques heures de différence...

### by lists of taxa
macrofauna_surface_guilds_family_tax_1 <- get.guilds(sciName = split_list[[1]], endpoint = endpoint_url)
macrofauna_surface_guilds_family_tax_2 <- get.guilds(sciName = split_list[[2]], endpoint = endpoint_url)
macrofauna_surface_guilds_family_tax_3 <- get.guilds(sciName = split_list[[3]], endpoint = endpoint_url)
macrofauna_surface_guilds_family_tax_4 <- get.guilds(sciName = split_list[[4]], endpoint = endpoint_url)
macrofauna_surface_guilds_family_tax_5 <- get.guilds(sciName = split_list[[5]], endpoint = endpoint_url)
macrofauna_surface_guilds_family_tax_6 <- get.guilds(sciName = split_list[[6]], endpoint = endpoint_url)
macrofauna_surface_guilds_family_tax_7 <- get.guilds(sciName = split_list[[7]], endpoint = endpoint_url)

macrofauna_surface_guilds_family_tax <- bind_rows(macrofauna_surface_guilds_family_tax_1, macrofauna_surface_guilds_family_tax_2, macrofauna_surface_guilds_family_tax_3, macrofauna_surface_guilds_family_tax_4, macrofauna_surface_guilds_family_tax_5, macrofauna_surface_guilds_family_tax_6, macrofauna_surface_guilds_family_tax_7)

n_distinct(macrofauna_surface_guilds_family_tax$queryName) # 50

write.csv(apply(macrofauna_surface_guilds_family_tax,2,as.character), "final_files/fun_table/family/fun_macrofauna_surface_guilds_family_update29-05-24.csv")

## diets
macrofauna_surface_diets_family_tax_1 <- get.diets(sciName = split_list[[1]], endpoint = endpoint_url)
macrofauna_surface_diets_family_tax_2 <- get.diets(sciName = split_list[[2]], endpoint = endpoint_url)
macrofauna_surface_diets_family_tax_3 <- get.diets(sciName = split_list[[3]], endpoint = endpoint_url)
macrofauna_surface_diets_family_tax_4 <- get.diets(sciName = split_list[[4]], endpoint = endpoint_url)
macrofauna_surface_diets_family_tax_5 <- get.diets(sciName = split_list[[5]], endpoint = endpoint_url)
macrofauna_surface_diets_family_tax_6 <- get.diets(sciName = split_list[[6]], endpoint = endpoint_url)
macrofauna_surface_diets_family_tax_7 <- get.diets(sciName = split_list[[7]], endpoint = endpoint_url)

macrofauna_surface_diets_family_tax <- bind_rows(macrofauna_surface_diets_family_tax_2, macrofauna_surface_diets_family_tax_3, macrofauna_surface_diets_family_tax_4, macrofauna_surface_diets_family_tax_5, macrofauna_surface_diets_family_tax_6, macrofauna_surface_diets_family_tax_7) # remove macrofauna_surface_diets_family_tax_1 because 0 obs.

n_distinct(macrofauna_surface_diets_family_tax$queryName) # 44

write.csv(apply(macrofauna_surface_diets_family_tax,2,as.character), "final_files/fun_table/family/fun_macrofauna_surface_diets_family_update29-05-24.csv")

## groups
macrofauna_surface_groups_family_tax_1 <- get.trophic.groups(sciName = split_list[[1]], endpoint = endpoint_url)
macrofauna_surface_groups_family_tax_2 <- get.trophic.groups(sciName = split_list[[2]], endpoint = endpoint_url)
macrofauna_surface_groups_family_tax_3 <- get.trophic.groups(sciName = split_list[[3]], endpoint = endpoint_url)
macrofauna_surface_groups_family_tax_4 <- get.trophic.groups(sciName = split_list[[4]], endpoint = endpoint_url)
macrofauna_surface_groups_family_tax_5 <- get.trophic.groups(sciName = split_list[[5]], endpoint = endpoint_url)
macrofauna_surface_groups_family_tax_6 <- get.trophic.groups(sciName = split_list[[6]], endpoint = endpoint_url)
macrofauna_surface_groups_family_tax_7 <- get.trophic.groups(sciName = split_list[[7]], endpoint = endpoint_url)

macrofauna_surface_groups_family_tax <- bind_rows(macrofauna_surface_groups_family_tax_1, macrofauna_surface_groups_family_tax_2, macrofauna_surface_groups_family_tax_3, macrofauna_surface_groups_family_tax_4, macrofauna_surface_groups_family_tax_5, macrofauna_surface_groups_family_tax_6, macrofauna_surface_groups_family_tax_7)

n_distinct(macrofauna_surface_groups_family_tax$queryName) # 50

write.csv(apply(macrofauna_surface_groups_family_tax,2,as.character), "final_files/fun_table/family/fun_macrofauna_surface_groups_family_update29-05-24.csv")

## interactions
macrofauna_surface_interactions_family_tax_1 <- get.interactions(sciName = split_list[[1]], endpoint = endpoint_url)
macrofauna_surface_interactions_family_tax_2 <- get.interactions(sciName = split_list[[2]], endpoint = endpoint_url)
macrofauna_surface_interactions_family_tax_3 <- get.interactions(sciName = split_list[[3]], endpoint = endpoint_url)
macrofauna_surface_interactions_family_tax_4 <- get.interactions(sciName = split_list[[4]], endpoint = endpoint_url)
macrofauna_surface_interactions_family_tax_5 <- get.interactions(sciName = split_list[[5]], endpoint = endpoint_url)
macrofauna_surface_interactions_family_tax_6 <- get.interactions(sciName = split_list[[6]], endpoint = endpoint_url)
macrofauna_surface_interactions_family_tax_7 <- get.interactions(sciName = split_list[[7]], endpoint = endpoint_url)

macrofauna_surface_interactions_family_tax <- bind_rows(macrofauna_surface_interactions_family_tax_1, macrofauna_surface_interactions_family_tax_2, macrofauna_surface_interactions_family_tax_3, macrofauna_surface_interactions_family_tax_5, macrofauna_surface_interactions_family_tax_6) # remove macrofauna_surface_diets_family_tax_4 and 7 because 0 obs.

n_distinct(macrofauna_surface_interactions_family_tax$queryName) # 6

write.csv(apply(macrofauna_surface_interactions_family_tax,2,as.character), "final_files/fun_table/family/fun_macrofauna_surface_interactions_family_update29-05-24.csv")
```

```{r}
# taxo filtrée et combinée avec les données d'abondance
tidytax_table <- read.csv("final_files/tidytax_update23-05-24.csv")[,-1]

macrofauna_surface_tidytax <- subset(tidytax_table, community == 'macrofauna_surface')

n_distinct(macrofauna_surface_tidytax$family) # 63

macrofauna_surface_guilds_family_tidytax <- get.guilds(sciName = unique(macrofauna_surface_tidytax$family), endpoint = endpoint_url)

n_distinct(macrofauna_surface_guilds_family_tidytax$queryName) # 57
```


